# see https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
[toolchain]
channel = "1.94.0"
components = ["rust-analyzer"]
profile = "default" # rustc, rust-std, cargo, rust-docs, rustfmt, clippy
